version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: karen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  backend:
    build: ./backend
    container_name: backend-container
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:test@postgres:5432/karen
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["npm", "start"]

  frontend:
    build: ./frontend
    container_name: frontend-container
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "start"]
    
volumes:
  postgres_data: